"""Write or check the isolated-environment setup cell of the modern image classification workshop.

The workshop notebook builds its own environment instead of installing into the kernel: a size- and
SHA-256-verified ``uv`` wheel creates a managed CPython 3.12.12 venv and installs the carried hash lock
(``tools/modern-image-workshop-requirements.lock``, ``uv pip compile --generate-hashes`` for CPython 3.12
on ``x86_64-manylinux_2_28``) with ``--require-hashes --only-binary :all:``. The next cell routes every
later code cell to one persistent worker process running that venv's interpreter.

The lock is carried as an implicitly concatenated run of pieces of at most 1,000 characters, split at
line boundaries, so no notebook line is long enough to stall the Colab editor. Only the setup cell
(id ``uv-install``) and ``metadata.dimer.carried_files`` are touched; the workshop has no other generator.

Usage::

    python tools/build_modern_workshop_runtime.py          # rewrite the setup cell
    python tools/build_modern_workshop_runtime.py --check  # exit 1 if the notebook is stale
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = ROOT / "tutorials" / "DIMER_Modern_Image_Classification_Workshop.ipynb"
LOCK = ROOT / "tools" / "modern-image-workshop-requirements.lock"
CELL_ID = "uv-install"
PIECE_LIMIT = 1000
MANAGED_PYTHON = "3.12.12"
UV_URL = (
    "https://files.pythonhosted.org/packages/1e/fd/432451d732917c49152a291de3ef171aa6b0f1a22d39780fb2c1f085ca4c/"
    "uv-0.12.15-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
)
UV_BYTES = 20081404
UV_SHA256 = "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60"

HEAD = '''# @title Infrastructure: build the isolated environment (uv, CPython 3.12.12, hash-locked wheels)
# dimer: kernel cell (runs in the notebook kernel, not in the isolated environment)
# Generated by tools/build_modern_workshop_runtime.py from tools/modern-image-workshop-requirements.lock.
import hashlib
import io
import os
import platform
import subprocess
import sys
import time
import urllib.error
import urllib.request
import zipfile
from pathlib import Path

MANAGED_PYTHON = {managed!r}
UV_URL = {url!r}
UV_BYTES = {uv_bytes}
UV_SHA256 = {uv_sha!r}
LOCK_NAME = "requirements.lock.txt"
LOCK_SHA256 = {lock_sha!r}
LOCKED_PACKAGES = {locked}
# The hash-locked requirements: `uv pip compile --generate-hashes` for CPython 3.12 on x86_64-manylinux_2_28,
# compiled from the notebook's direct pins (listed again in Section 4).
# Carried in pieces of at most 1,000 characters.
LOCK_TEXT = (
'''

TAIL = '''
)

SKIP_INSTALL = os.environ.get("DIMER_NOTEBOOK_CI_PREINSTALLED") == "1"
ISOLATED_ENV = Path(os.environ.get("DIMER_ISOLATED_ENV", "dimer_isolated_env")).resolve()
ISOLATED_PYTHON = ISOLATED_ENV / "bin" / "python"
ISOLATED_TOOLS = ISOLATED_ENV.with_name(ISOLATED_ENV.name + "_tools")

if SKIP_INSTALL:
    print("DIMER_NOTEBOOK_CI_PREINSTALLED=1: the pins are already installed; "
          "the notebook runs in this kernel.")
else:
    if platform.system() != "Linux" or platform.machine() != "x86_64":
        raise RuntimeError("This notebook needs a Linux x86_64 runtime (Google Colab, Kaggle or Linux "
                           "Jupyter): its locked environment is built from manylinux x86_64 wheels.")
    setup_started = time.perf_counter()
    if hashlib.sha256(LOCK_TEXT.encode("utf-8")).hexdigest() != LOCK_SHA256:
        raise RuntimeError("The carried lock does not match its digest: "
                           "restore this cell from the repository.")
    ISOLATED_TOOLS.mkdir(parents=True, exist_ok=True)
    lock_path = ISOLATED_TOOLS / LOCK_NAME
    lock_path.write_text(LOCK_TEXT, encoding="utf-8", newline="\\n")
    for attempt in range(3):
        try:
            with urllib.request.urlopen(UV_URL, timeout=90) as response:
                wheel = response.read(UV_BYTES + 1)
            break
        except (urllib.error.URLError, TimeoutError, ConnectionError):
            if attempt == 2:
                raise
            time.sleep(2**attempt)
    if len(wheel) != UV_BYTES or hashlib.sha256(wheel).hexdigest() != UV_SHA256:
        raise RuntimeError("The pinned uv wheel failed its size/SHA-256 check: refusing to run it. "
                           "Run this cell again; if it repeats, the download is being altered.")
    with zipfile.ZipFile(io.BytesIO(wheel)) as archive:
        member = next(name for name in archive.namelist() if name.endswith(".data/scripts/uv"))
        uv = ISOLATED_TOOLS / "uv"
        uv.write_bytes(archive.read(member))
    uv.chmod(0o700)
    # uv gets no kernel Python path; the managed interpreter is downloaded once and reused on a re-run.
    uv_env = dict(os.environ)
    for name in ("PYTHONPATH", "PYTHONHOME", "PYTHONSTARTUP"):
        uv_env.pop(name, None)
    if not ISOLATED_PYTHON.is_file():
        print("Creating the isolated Python", MANAGED_PYTHON, "environment...", flush=True)
        subprocess.run([str(uv), "venv", "--quiet", "--managed-python", "--python", MANAGED_PYTHON,
                        str(ISOLATED_ENV)], env=uv_env, check=True)
    isolated_version = subprocess.run(
        [str(ISOLATED_PYTHON), "-c", "import platform; print(platform.python_version())"],
        env=uv_env, check=True, capture_output=True, text=True,
    ).stdout.strip()
    if isolated_version != MANAGED_PYTHON:
        raise RuntimeError(f"{ISOLATED_ENV} holds Python {isolated_version}, not {MANAGED_PYTHON}: "
                           "delete that folder (or start a fresh runtime) and run this cell again.")
    print("Installing the hash-locked packages "
          "(several minutes on a fresh runtime; the CUDA wheels are large)...", flush=True)
    subprocess.run([str(uv), "pip", "install", "--quiet", "--python", str(ISOLATED_PYTHON),
                    "--require-hashes", "--only-binary", ":all:", "--index-url", "https://pypi.org/simple",
                    "-r", str(lock_path)], env=uv_env, check=True)
    print({"isolated_environment": str(ISOLATED_ENV), "isolated_python": isolated_version,
           "kernel_python": platform.python_version(), "locked_packages": LOCKED_PACKAGES,
           "setup_seconds": round(time.perf_counter() - setup_started)})'''


def pieces(text: str, limit: int = PIECE_LIMIT) -> list[str]:
    """Split at line boundaries into runs of at most ``limit`` characters (a longer line is cut)."""
    out: list[str] = []
    current = ""
    for line in text.splitlines(keepends=True):
        while len(line) > limit:
            if current:
                out.append(current)
                current = ""
            out.append(line[:limit])
            line = line[limit:]
        if current and len(current) + len(line) > limit:
            out.append(current)
            current = ""
        current += line
    if current:
        out.append(current)
    return out


def lock_text() -> str:
    data = LOCK.read_bytes()
    if b"\r" in data:
        raise SystemExit(f"{LOCK} must use LF line endings")
    return data.decode("utf-8")


def locked_packages(text: str) -> int:
    return len(re.findall(r"^[A-Za-z0-9][A-Za-z0-9._-]*==", text, flags=re.MULTILINE))


def cell_source(text: str) -> str:
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    head = HEAD.format(
        managed=MANAGED_PYTHON,
        url=UV_URL,
        uv_bytes=UV_BYTES,
        uv_sha=UV_SHA256,
        lock_sha=digest,
        locked=locked_packages(text),
    )
    body = "\n".join(f"    {piece!r}" for piece in pieces(text))
    return head + body + TAIL


def render(notebook: dict) -> dict:
    text = lock_text()
    cells = [c for c in notebook["cells"] if c.get("id") == CELL_ID]
    if len(cells) != 1:
        raise SystemExit(f"expected exactly one cell with id {CELL_ID!r}, found {len(cells)}")
    cells[0]["source"] = cell_source(text).splitlines(keepends=True)
    notebook["metadata"]["dimer"]["carried_files"] = {
        "requirements.lock.txt": {
            "source": LOCK.relative_to(ROOT).as_posix(),
            "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest(),
            "locked_packages": locked_packages(text),
        }
    }
    return notebook


def dump(notebook: dict) -> str:
    return json.dumps(notebook, indent=2, ensure_ascii=False)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the notebook setup cell is stale")
    args = parser.parse_args(argv)
    current = NOTEBOOK.read_text(encoding="utf-8")
    expected = dump(render(json.loads(current)))
    if args.check:
        if current != expected:
            print(f"STALE: {NOTEBOOK.name} setup cell differs from {LOCK.name}; run without --check")
            return 1
        print(f"OK: {NOTEBOOK.name} setup cell matches {LOCK.name}")
        return 0
    NOTEBOOK.write_bytes(expected.encode("utf-8"))
    print(f"wrote {NOTEBOOK.name} ({len(expected.encode('utf-8'))} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
